/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikeuanganpribadi;

import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.text.*;

/**
 *
 * @author USER
 */
public class AplikasiKeuanganPribadiForm extends javax.swing.JFrame {

    DefaultTableModel model;
    double totalPemasukan = 0;
    double totalPengeluaran = 0;
    private Object[] lastDeletedRow = null; // Variabel untuk menyimpan data baris yang dihapus
    private javax.swing.JLabel jLabelStatusBar;


    public AplikasiKeuanganPribadiForm() {
        initComponents();
       model = (DefaultTableModel) jTableoutput.getModel();
model.setColumnIdentifiers(new String[]{"Kategori", "Nominal", "Tanggal", "Keterangan"});

        applyNumberFilter(jTextFieldinputnominal);
        jButtonImport.addActionListener(evt -> jButtonImportActionPerformed(evt));
        jTableoutput.revalidate();
jTableoutput.repaint();

        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBoxkategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaketerangan = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableoutput = new javax.swing.JTable();
        jTextFieldcari = new javax.swing.JTextField();
        jButtoncari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelPemasukan = new javax.swing.JLabel();
        jButtontambah = new javax.swing.JButton();
        jButtonubah = new javax.swing.JButton();
        jButtonhapus = new javax.swing.JButton();
        jButtonexport = new javax.swing.JButton();
        jButtonundo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelrataratapemasukan = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelpengeluaran = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelrataratapengeluaran = new javax.swing.JLabel();
        jTextFieldinputnominal = new javax.swing.JTextField();
        jButtonImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLIKASI KEUANGAN PRIBADI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(340, 340, 340))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Pilih Kategori Transaksi :");

        jLabel3.setText("Masukan Jumlah transaksi :");

        jLabel4.setText("Masukan tanggal :");

        jComboBoxkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));

        jLabel5.setText("Keterangan Traksaksi :");

        jTextAreaketerangan.setColumns(20);
        jTextAreaketerangan.setRows(5);
        jScrollPane1.setViewportView(jTextAreaketerangan);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel"));

        jTableoutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableoutput);

        jButtoncari.setText("Cari");
        jButtoncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldcari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtoncari)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncari))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPemasukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPemasukan.setText("Pemasukan RP.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPemasukan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPemasukan)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButtontambah.setText("Tambah");
        jButtontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontambahActionPerformed(evt);
            }
        });

        jButtonubah.setText("Ubah");
        jButtonubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonubahActionPerformed(evt);
            }
        });

        jButtonhapus.setText("Hapus");
        jButtonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhapusActionPerformed(evt);
            }
        });

        jButtonexport.setText("     Export    ");
        jButtonexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexportActionPerformed(evt);
            }
        });

        jButtonundo.setText("Undo hapus");
        jButtonundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonundoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelrataratapemasukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelrataratapemasukan.setText("Rata-rata pemasukan RP.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelrataratapemasukan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelrataratapemasukan)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelpengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelpengeluaran.setText("Pengeluaran Rp.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelpengeluaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelpengeluaran)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelrataratapengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelrataratapengeluaran.setText("Rata-rata pengeluaran RP.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelrataratapengeluaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelrataratapengeluaran)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonImport.setText("Import");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButtonubah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonundo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonexport, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonImport, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxkategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldinputnominal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldinputnominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtontambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonubah))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonhapus)
                            .addComponent(jButtonexport)
                            .addComponent(jButtonundo)
                            .addComponent(jButtonImport))
                        .addGap(21, 21, 21)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncariActionPerformed
    String keyword = jTextFieldcari.getText().toLowerCase();
    for (int i = 0; i < jTableoutput.getRowCount(); i++) {
        for (int j = 0; j < jTableoutput.getColumnCount(); j++) {
            String cellValue = jTableoutput.getValueAt(i, j).toString().toLowerCase();
            if (cellValue.contains(keyword)) {
                jTableoutput.setRowSelectionInterval(i, i);
                return;
            }
        }
    }
    JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Pencarian", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtoncariActionPerformed
private void applyNumberFilter(JTextField textField) {
    textField.addKeyListener(new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            // Hanya izinkan angka dan backspace
            if (!Character.isDigit(c) && c != '\b') {
                e.consume(); // Abaikan input
                JOptionPane.showMessageDialog(
                    textField,
                    "Hanya angka yang diperbolehkan!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        }
    });
}


    private void jButtontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontambahActionPerformed
    String kategori = jComboBoxkategori.getSelectedItem().toString();
    String nominalInput = jTextFieldinputnominal.getText().replace("Rp", "").replace(",", "").trim(); // Hapus "Rp" dan spasi
    Date tanggal = jDateChooser2.getDate();
    String keterangan = jTextAreaketerangan.getText();

    // Validasi input nominal
    if (nominalInput.isEmpty() || !nominalInput.matches("\\d+")) { // Pastikan hanya angka
        JOptionPane.showMessageDialog(this, "Nominal harus diisi dengan angka lebih besar dari nol!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validasi input tanggal
    if (tanggal == null || tanggal.after(new Date())) {
        JOptionPane.showMessageDialog(this, "Tanggal tidak boleh melebihi hari ini!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tambah data ke tabel
    double jumlah = Double.parseDouble(nominalInput);
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    model.addRow(new Object[]{kategori, "Rp " + String.format("%.0f", jumlah), sdf.format(tanggal), keterangan});

    // Perbarui riwayat
    updateRiwayat();
    clearInput();
    }//GEN-LAST:event_jButtontambahActionPerformed

    private void jButtonubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonubahActionPerformed
   int selectedRow = jTableoutput.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String kategori = jComboBoxkategori.getSelectedItem().toString();
    String nominalInput = jTextFieldinputnominal.getText().replace("Rp", "").replace(",", "").trim(); // Hapus "Rp" dan spasi
    Date tanggal = jDateChooser2.getDate();
    String keterangan = jTextAreaketerangan.getText();

    // Validasi input nominal
    if (nominalInput.isEmpty() || !nominalInput.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Nominal harus diisi dengan angka lebih besar dari nol!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validasi input tanggal
    if (tanggal == null || tanggal.after(new Date())) {
        JOptionPane.showMessageDialog(this, "Tanggal tidak boleh melebihi hari ini!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Ubah data di tabel
    double jumlah = Double.parseDouble(nominalInput);
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    model.setValueAt(kategori, selectedRow, 0);
    model.setValueAt("Rp " + String.format("%.0f", jumlah), selectedRow, 1);
    model.setValueAt(sdf.format(tanggal), selectedRow, 2);
    model.setValueAt(keterangan, selectedRow, 3);

    // Perbarui riwayat
    updateRiwayat();
    clearInput();
    }//GEN-LAST:event_jButtonubahActionPerformed
     
    private void jButtonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhapusActionPerformed
        // TODO add your handling code here:  
      int selectedRow = jTableoutput.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        // Simpan data yang dihapus untuk undo
        lastDeletedRow = new Object[]{
            model.getValueAt(selectedRow, 0),
            model.getValueAt(selectedRow, 1),
            model.getValueAt(selectedRow, 2),
            model.getValueAt(selectedRow, 3)
        };

        // Hapus data dari tabel
        model.removeRow(selectedRow);

        // Perbarui riwayat
        updateRiwayat();
    }
    }//GEN-LAST:event_jButtonhapusActionPerformed

    private void jButtonexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexportActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
    int option = fileChooser.showSaveDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
        try (FileWriter writer = new FileWriter(fileChooser.getSelectedFile() + ".csv")) {
            DefaultTableModel model = (DefaultTableModel) jTableoutput.getModel();
            writer.append("Kategori,Nominal,Tanggal,Keterangan\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                  writer.append("\"").append(model.getValueAt(i, j).toString()).append("\"").append(",");
                }
                writer.append("\n");
            }
            JOptionPane.showMessageDialog(this, "Data berhasil diexport!", "Export", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal menulis file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonexportActionPerformed

    private void jButtonundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonundoActionPerformed
        // TODO add your handling code here:
         if (lastDeletedRow == null) {
        JOptionPane.showMessageDialog(this, "Tidak ada data untuk di-undo!", "Info", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // Tambahkan kembali data yang dihapus
    model.addRow(lastDeletedRow);
    lastDeletedRow = null; // Bersihkan cache setelah undo

    // Perbarui riwayat
    updateRiwayat();
    }//GEN-LAST:event_jButtonundoActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        // TODO add your handling code here:                                            
     JFileChooser fileChooser = new JFileChooser();
    int option = fileChooser.showOpenDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
        try (BufferedReader reader = new BufferedReader(new FileReader(fileChooser.getSelectedFile()))) {
            String line;
            // Lewati header (baris pertama)
            reader.readLine();
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) continue; // Lewati baris kosong

                // Debugging: Cetak baris yang sedang diproses
                System.out.println("Membaca baris: " + line);

                String[] data = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1); // Parsing CSV
                if (data.length == 4) {
                    String kategori = data[0].replace("\"", "").trim();
                    String nominal = data[1].replace("\"", "").replace("Rp", "").trim();
                    String tanggal = data[2].replace("\"", "").trim();
                    String keterangan = data[3].replace("\"", "").trim();

                    // Debugging: Cetak data yang diparsing
                    System.out.println("Kategori: " + kategori + ", Nominal: " + nominal + ", Tanggal: " + tanggal + ", Keterangan: " + keterangan);

                    // Validasi nominal
                    if (!nominal.matches("\\d+")) {
                        JOptionPane.showMessageDialog(this, "Nominal tidak valid: " + nominal, "Error", JOptionPane.ERROR_MESSAGE);
                        continue;
                    }

                    // Validasi tanggal
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                    Date parsedDate;
                    try {
                        parsedDate = sdf.parse(tanggal);
                        System.out.println("Tanggal valid: " + sdf.format(parsedDate));
                    } catch (Exception e) {
                        System.out.println("Tanggal tidak valid: " + tanggal);
                        e.printStackTrace();
                        continue;
                    }

                    // Tambahkan data ke tabel
                    model.addRow(new Object[] {
                        kategori,
                        "Rp " + nominal,
                        sdf.format(parsedDate),
                        keterangan
                    });
                    System.out.println("Data berhasil ditambahkan ke tabel.");
                } else {
                    System.out.println("Baris tidak valid: " + line);
                }
            }

            // Tambahkan di sini setelah data selesai diproses
            jTableoutput.revalidate();
            jTableoutput.repaint();
            jTableoutput.setModel(model);

            // Perbarui total pemasukan dan pengeluaran
            updateRiwayat();

            JOptionPane.showMessageDialog(this, "Data berhasil diimpor!", "Import", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membaca file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonImportActionPerformed

private void updateRiwayat() {
    double jumlahPemasukan = 0;
    double jumlahPengeluaran = 0;
    int jumlahTransaksiPemasukan = 0;
    int jumlahTransaksiPengeluaran = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        String kategori = model.getValueAt(i, 0).toString();
        String nominalStr = model.getValueAt(i, 1).toString().replace("Rp", "").replace(",", "").trim();
        double nominal = Double.parseDouble(nominalStr);

        if (kategori.equals("Pemasukan")) {
            jumlahPemasukan += nominal;
            jumlahTransaksiPemasukan++;
        } else if (kategori.equals("Pengeluaran")) {
            jumlahPengeluaran += nominal;
            jumlahTransaksiPengeluaran++;
        }
    }

    // Hitung rata-rata pemasukan dan pengeluaran
    double rataRataPemasukan = (jumlahTransaksiPemasukan > 0) ? (double) jumlahPemasukan / jumlahTransaksiPemasukan : 0;
    double rataRataPengeluaran = (jumlahTransaksiPengeluaran > 0) ? (double) jumlahPengeluaran / jumlahTransaksiPengeluaran : 0;

    // Format dan perbarui JLabel
    jLabelPemasukan.setText("Pemasukan: Rp " + String.format("%.0f", jumlahPemasukan));
    jLabelpengeluaran.setText("Pengeluaran: Rp " + String.format("%.0f", jumlahPengeluaran));
    jLabelrataratapemasukan.setText("Rata-rata Pemasukan: Rp " + String.format("%.0f", rataRataPemasukan));
    jLabelrataratapengeluaran.setText("Rata-rata Pengeluaran: Rp " + String.format("%.0f", rataRataPengeluaran));
}



private void clearInput() {
    jTextFieldinputnominal.setText("");
    jDateChooser2.setDate(new Date());
    jTextAreaketerangan.setText("");
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganPribadiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganPribadiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganPribadiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganPribadiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKeuanganPribadiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtoncari;
    private javax.swing.JButton jButtonexport;
    private javax.swing.JButton jButtonhapus;
    private javax.swing.JButton jButtontambah;
    private javax.swing.JButton jButtonubah;
    private javax.swing.JButton jButtonundo;
    private javax.swing.JComboBox<String> jComboBoxkategori;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPemasukan;
    private javax.swing.JLabel jLabelpengeluaran;
    private javax.swing.JLabel jLabelrataratapemasukan;
    private javax.swing.JLabel jLabelrataratapengeluaran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableoutput;
    private javax.swing.JTextArea jTextAreaketerangan;
    private javax.swing.JTextField jTextFieldcari;
    private javax.swing.JTextField jTextFieldinputnominal;
    // End of variables declaration//GEN-END:variables

}
